name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.8+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a543d5009b01a03d3bd766c9abfc5fead3056d2807d4339cd7a96e9f54ff8f61"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
