name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.16+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bebd27901d25c2bdd107bb30bca6492b68e0f8d0e4a6370bb429dab4f21d72f"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
