name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.4+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6773227fb7a57f4798109cd06a2437320ffbb4f8555ff5b9bb20eaf6e04c83ce"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
