name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.8+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33d40ae1b8da384839920403c8308bdeca384dfdd596ce0418544c0af491be92"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
