name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.12+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94eba85129a0ba121ec107bde5e12ff71101f49e3ef5dc22accceb1091435dda"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
