name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.3+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eae9527a3710f47c6489f57042c8115427bc923503da6cc7393d01d7d942f89"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
