name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.10+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93c323e9fd799d6dbddb49bcefb65095864700c0ef57488996bfe4208879df02"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
