name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.12+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c235573415275d1a93dcc1f09a642ff5e2be628733096c6fd81b3573d8693510"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
