name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.4+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dec2a42f110c84909234fdb0d47b6249e6cc6fa747b35b4f255f445682bfae9d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
