name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.6+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "049fa3b74b4755842d6e11105b7a3e6ef4e0cef119748a3ed2acb80ca0bb550e"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
