name = "Modpack"
author = "pcal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7504aa617cce4fcc9cbbd9926ac37edbfb32941028515baa1662f8a56b87d4dc"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
