name = "Modpack"
author = "pcal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5821516fe815f3540a2f424f128e644c8f9fc30223e4db13482de8a54d6de38"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
