name = "Modpack"
author = "pcal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83013c6e6cf524410bb6197d4108f75bc99e2d362b873a8446a355aee01f5e0"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
