name = "Modpack"
author = "pcal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b270b4fffd37fff26829deebced0c47fd27b7615447744fd3d8ed08f01449655"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
