name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.4+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67bebdf3775d4b18b001b4547f9ca35522d0fc2b0eb293fec6ac315c5cf7a88d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
