name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.12+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52a91495ad335abc85edc4046cba0378bfca0bf3793518595386c8c53b45805c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
