name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.10+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c4c82102c6d3bd7ebf58e78ab695128edc4617b5fa222ed0bc9959d8f8f19bb"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
