name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.12+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12f1fb7f9c289ef0a48d71a6d13997eb810ffcdc6c334311f2c13f250b850a73"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
