name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.10+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aa2b23b21c783dbd0f338fe61862baa9ce24a33e7259b5ea706a6a2ef025949"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
