name = "CrazyDavesModpack-client"
author = "pcal"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b18f90db120a27e7eb57fac756f37f39329ead3ba399ec7118d48551ecb5ff0a"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
