name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.4+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8a1c2e60b4af3f4ea3f3e00aaec85c79aace5c83976e4d482beffbbf3bd1dbf"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
