name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a55263d305fb639279ae18a7cbae85b899eb5974055e982245f1ec0391b6bc9"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
