name = "CrazyDavesModpack-host"
author = "pcal"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "217c620427006ae54b136b585bf02e8f0c8f2672194a27c4e2721db9e096cec0"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
