#
# SAMPLE CONFIGURATION - uncomment and edit
#

rules:
 - name: Minecraft thinks ocelots are MONSTERs
   what: ALLOW_SPAWN
   when:
     entityId: ['minecraft:ocelot']

#
# island borders are basically
# x: [-4, 200]
# z: [-256, -502]
#

 - name: Safe Spawn
   what: DISALLOW_SPAWN
   when:
     spawnGroup: [MONSTER]
     dimensionId: ['minecraft:overworld']
     blockX: [-128, 328]
     blockY: [30, MAX]
     blockZ: [-628, -128]



#
#     blockX: [-408, 777]
#     blockY: [33, MAX]
#     blockZ: [-963, -112]

#-261 68 -963
#690 63 -966
#777 64 -157
#-178 64 -114 side
#-246 64 -112 corner
#-313 62 -529
#-408 63 -832





#
# DOCUMENTATION
#

#
# The top-level 'rules' configuration element contains a list of filtering rules that are checked to see whether
# a new mob should be allowed to spawn.
#
#
# Each rule has three keys:
#     name - A human-readable name for the rule, useful for documentation and debugging.
#     what - Indicates what to do when the rule matches.  Must be DISALLOW_SPAWN or ALLOW_SPAWN.
#     when - A list of conditions that must be true in order for the rule to match.
#
# The 'when' section provides a set of conditions that must all be true in order for the rule to be a match.
# It may contain any of the following keys:
#
# spawnGroup
#     List of net.minecraft.entity.SpawnGroup values, such as MONSTER or CREATURE.  The condition is true when
#     the mob to be spawned is in one of the listed groups.
#
# entityId
#     List of entity ids, e.g. 'minecraft:zombie'.  The condition is true when the id of the mob to be spawned is
#     in the list.
#
# blockX
# blockY
# blockZ
#    List of two integers specifying a range.  True when the mob's spawning position on the given axis (X, Y or Z)
#    is within the provided range.  'MIN' may be used for the first value and 'MAX' may be used for the second.
#
# worldName
#     List of world names, e.g., 'My World'.  True if mob is spawning in a listed world.  Useful if you need
#     to the mob filtering to specific worlds.
#
# dimensionId
#     List of dimension identifiers, e.g., 'minecraft:overworld'.  True if mob is spawning in a listed dimension.
#
# biomeId
#     List of biome identifiers, e.g., 'minecraft:ocean'.  True if mob is spawning in a listed biome.
#
# blockId
#     List of block identifiers, e.g., 'minecraft:cobblestone'.  True if mob is spawning on a listed block type.
#
# lightLevel
#     Two integers between 0 and 16.  True if mob is spawning in a lightLevel within the range.
#
# timeOfDay
#     Two integers between 0 and 24000.  True if mob is spawning at a timeOfDay within the range.
#



#
# NOTES
#
# Filter rules are processed in order and processing stops as soon as a matching rule is found.  This means you can
# put blanket exclusions at the top of your rules list, e.g.,
#
# rules:
#  - name: Always do normal spawning in Nether and End
#    what: ALLOW_SPAWN
#    when:
#      dimensionId: ['minecraft:nether', 'minecreate:the_end']
#
# ...more rules
#



#
# logLevel
#     This sets log4j logging level for the mod.  Set to 'DEBUG' to log each time a spawn is disallowed.
#     Set to 'TRACE' to see detailed logging on rule evaluation.  Be careful - this can quickly fill up your logfiles.
#
#logLevel: DEBUG
