name = "CrazyDavesModpack-server"
author = "pcal"
version = "0.0.3+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee6233bc2f50f81dd812ea321fde6eb6e4c68a663d81b41fc8f6f158160af961"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
