name = "CrazyDavesModpack-server"
author = "pcal"
version = "0.0.5+1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6839cf24457a2276249fc31a40dc3326e83293db8dbde92528844adfe90b56a1"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
