name = "CrazyDavesModpack-server"
author = "pcal"
version = "0.0.10+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b954e4242f5efff3d64b5fae332102dd615934fc185c9d60aa3b1e5f7cb31a51"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
