name = "Modpack"
author = "pcal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c8a312d7d5717b80cf6bc3e92a5f80fee8cba972d87a0582cc68663a88a5ad3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
