name = "CrazyDavesModpack-server"
author = "pcal"
version = "0.0.15+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebc156fd355290dedf3f8c7bcf748cf78e2621940c560dbc2b101fb7c223547f"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
